### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #22

### CODE REVIEW

**Comment by Keruspe** [comment]
@Stupremee @vertexclique without this bastion pulls in two versions of its executor

**Review by Stupremee — APPROVED** [review]

**Comment by Keruspe** [comment]
Thanks! Would be awesome to see a new release with this!

**Comment by Stupremee** [comment]
Yea I will try to release in the next few days 👍

**Comment by vertexclique** [comment]
Oh, thanks! Super idea.

**Pull request merged**
